### ISSUE TITLE
Enforcing action when time before CP gets captured is 10 seconds or less

### ISSUE THREAD

**Issue by xtr3m3k1ll4h** [beijind/SAMPBulletproof#4]
When time left before cp gets captured is 10 seconds or less, make things tense so that people don't ignore CP.

You could do any of these: 
a) Use a bit more dramatic sound like area69 alarm sound probably (but it has to be stopped too because it has constant loop)
b) Make a 500ms timer so you hear CP sound twice a second 
c) Use ganga area flash with red color
d) Flash CP textdraw on screen with red color... 

I hope you get the idea that we basically need something so that people don't ignore CP when it is about to be taken

**Comment by Tadas3333** [comment]
Yeah, I agree. This should be done. I also remember on deadly combinations there was this thing that whole screen flashed with big red box, but this might be too much. Will think about the best option.
