### ISSUE TITLE
Different colors for attacking and defending team leaders

### ISSUE THREAD

**Issue by xtr3m3k1ll4h** [beijind/SAMPBulletproof#5]
Right now, leading a team changes your color to light green irrespective of team. My suggestion is to change team leader color to a bit more team-friendly color. For example, an attacker leading should have his playercolor as a shade of red (probably pink) while a defender leading should have a shade of blue (probably aqua)

**Comment by Tadas3333** [comment]
Good idea! I thought about it in the past, this should be done.
